#!/usr/bin/env python3
"""Generate problem inputs with known, planted matches.

Benchmarking and testing both need inputs whose answer is known in advance and
whose size can be dialled up past what anyone would write by hand. A planted
occurrence gives the search something real to find, and --plant-rate controls
how much of the placement space is actually scanned before the answer turns
up -- which is the single biggest factor in how long a run takes, and therefore
something a benchmark must be able to hold fixed.

Examples:
    # small fixture with a guaranteed match, reproducible
    tools/gen_input.py --pictures 4 --picture-size 32 --objects 3 --seed 7

    # a benchmark-scale input, nothing planted (worst case: full scan)
    tools/gen_input.py --pictures 8 --picture-size 1024 --objects 6 \\
                       --object-size 24 --plant-rate 0 -o bench/large.txt
"""

from __future__ import annotations

import argparse
import random
import sys
from typing import List, TextIO

PICTURE_ID_BASE = 100
OBJECT_ID_BASE = 200


def parse_args(argv: List[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a submatrix-search problem with planted matches.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--pictures", type=int, default=4, help="number of pictures")
    parser.add_argument("--picture-size", type=int, default=64, help="picture side length")
    parser.add_argument("--objects", type=int, default=4, help="number of objects")
    parser.add_argument("--object-size", type=int, default=8, help="object side length")
    parser.add_argument("--threshold", type=float, default=1.0, help="matching threshold")
    parser.add_argument(
        "--value-max", type=int, default=255, help="picture/object values are drawn from [1, MAX]"
    )
    parser.add_argument(
        "--plant-rate",
        type=float,
        default=0.5,
        help="fraction of pictures that contain a planted occurrence (0..1)",
    )
    parser.add_argument(
        "--plant-position",
        choices=("random", "late"),
        default="random",
        help="'late' plants near the end of the scan, forcing a near-full search",
    )
    parser.add_argument("--seed", type=int, default=1, help="PRNG seed (output is reproducible)")
    parser.add_argument("-o", "--output", default="-", help="output path, '-' for stdout")
    args = parser.parse_args(argv)

    if args.object_size > args.picture_size:
        parser.error("--object-size must not exceed --picture-size")
    if not 0.0 <= args.plant_rate <= 1.0:
        parser.error("--plant-rate must be between 0 and 1")
    if args.value_max < 1:
        # Values start at 1 so that generated inputs do not silently depend on
        # the zero-element policy; zero handling has its own fixture.
        parser.error("--value-max must be >= 1")
    return args


def write_matrix(out: TextIO, data: List[int], side: int) -> None:
    for row in range(side):
        out.write("  " + " ".join(str(v) for v in data[row * side : (row + 1) * side]) + "\n")


def main(argv: List[str]) -> int:
    args = parse_args(argv)
    rng = random.Random(args.seed)

    objects = [
        [rng.randint(1, args.value_max) for _ in range(args.object_size**2)]
        for _ in range(args.objects)
    ]

    pictures = []
    planted = []
    span = args.picture_size - args.object_size + 1
    for index in range(args.pictures):
        data = [rng.randint(1, args.value_max) for _ in range(args.picture_size**2)]
        note = None
        if objects and rng.random() < args.plant_rate:
            which = rng.randrange(len(objects))
            if args.plant_position == "late":
                row = rng.randrange(max(1, span * 3 // 4), span)
                col = rng.randrange(max(1, span * 3 // 4), span)
            else:
                row, col = rng.randrange(span), rng.randrange(span)
            for y in range(args.object_size):
                start = (row + y) * args.picture_size + col
                data[start : start + args.object_size] = objects[which][
                    y * args.object_size : (y + 1) * args.object_size
                ]
            note = (OBJECT_ID_BASE + which, row, col)
        pictures.append(data)
        planted.append(note)

    out = sys.stdout if args.output == "-" else open(args.output, "w", encoding="utf-8")
    try:
        out.write(f"# generated by tools/gen_input.py (seed {args.seed})\n")
        out.write("# planted occurrences (the lowest object id at the lowest\n")
        out.write("# row-major position is what the search should report):\n")
        for index, note in enumerate(planted):
            picture_id = PICTURE_ID_BASE + index
            if note is None:
                out.write(f"#   picture {picture_id}: nothing planted\n")
            else:
                out.write(f"#   picture {picture_id}: object {note[0]} at ({note[1]},{note[2]})\n")
        out.write(f"\n{args.threshold}\n{args.pictures}\n")
        for index, data in enumerate(pictures):
            out.write(f"\n{PICTURE_ID_BASE + index} {args.picture_size}\n")
            write_matrix(out, data, args.picture_size)
        out.write(f"\n{args.objects}\n")
        for index, data in enumerate(objects):
            out.write(f"\n{OBJECT_ID_BASE + index} {args.object_size}\n")
            write_matrix(out, data, args.object_size)
    finally:
        if out is not sys.stdout:
            out.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
